const d = document

const title = d.getElementById("title")
const date = d.getElementById("date")
const mood = d.getElementById("mood")
const content = d.getElementById("content")
const tags = d.getElementById("tags")

date.value = new Date().toISOString().split('T')[0]



// journal colors json
const colors = {
    "happy": { "bg": "#FFB30022", "text": "#FFD54F", "border": "#FFB30055" },
    "sad": { "bg": "#0091EA22", "text": "#40C4FF", "border": "#0091EA55" },
    "angry": { "bg": "#D5000022", "text": "#FF5252", "border": "#D5000055" },
    "calm": { "bg": "#00C85322", "text": "#69F0AE", "border": "#00C85355" },
    "anxious": { "bg": "#7C4DFF22", "text": "#B388FF", "border": "#7C4DFF55" },
    "excited": { "bg": "#FF572222", "text": "#FF8A65", "border": "#FF572255" },
    "motivated": { "bg": "#FF408122", "text": "#FF80AB", "border": "#FF408155" },
    "tired": { "bg": "#607D8B22", "text": "#90A4AE", "border": "#607D8B55" },
    "focused": { "bg": "#00E5FF22", "text": "#18FFFF", "border": "#00E5FF55" },
    "lonely": { "bg": "#6D4C4122", "text": "#BCAAA4", "border": "#6D4C4155" },
    "grateful": { "bg": "#AEEA0022", "text": "#CCFF90", "border": "#AEEA0055" },
    "confused": { "bg": "#F5005722", "text": "#FF80AB", "border": "#F5005755" },
    "other": { "bg": "#BDBDBD22", "text": "#E0E0E0", "border": "#BDBDBD55" }
}




// this function will return the color for the journals in the left side based on the mood of the journal, if the mood is not found in the colors object, it will return the default color (white background, black text and gray border)
const colorForJournal = (mood = "other") => {
    return colors[mood.toLowerCase()]
}





// delete journal by id
// fetching all the journals
// then filtering all the journals whose id is not equal to the id passed in argument and then saving the resulting array
const deleteJournalById = (id) => {
    const journals = JSON.parse(localStorage.getItem("journals")) || []
    const filtered = journals.filter(entry => entry.id !== id)
    localStorage.setItem("journals", JSON.stringify(filtered))
}




// Saving the journal in local storage
const saveJournal = () => {

    if (!title.value || !mood.value || !content.value) {
        alert("All fields are required")
        return
    }

    const journals = JSON.parse(localStorage.getItem("journals")) || []

    journals.push({
        id: Math.random().toString(36), // base 36 here is used to change the numeric generated by random() into an encoded string with base 36 (it will use numbers, all 26 lowercase alphabets)
        title: title.value,
        date: date.value,
        mood: mood.value || "other",
        content: content.value.trim(),
        tags: tags.value
            .split(",")
            .map((tag) => tag.trim())
            .filter(tag => tag !== "")
    })

    localStorage.setItem("journals", JSON.stringify(journals))
    clearForm();

}

const form = d.querySelector("form")


form.addEventListener("submit", (e) => {
    e.preventDefault()
    saveJournal();
    renderJournals();
})




// render function for rendering the journals in the left space
const renderJournals = () => {
    const journals = JSON.parse(localStorage.getItem("journals")) || [];
    const journalList = d.querySelector(".entries-list ul")
    console.log(journalList)

    // if there are no thoughts/journals present in our localStrorage then the below message will be shown on the screen
    if (journals.length === 0) {
        journalList.innerHTML = `
            <div class="empty-state">
                <div class="empty-state-badge">A Mind Unfiltered</div>
                <h2>No entries yet</h2>
                <p>Write your first thought.</p>
            </div>
        `
        return
    }

    // if thoughts are present in the storage then we are rendering as an li tag each with specialized colors based on mood
    journalList.innerHTML = journals.map(journal => {
        const color = colorForJournal(journal.mood.split(" ")[1]) || colors["other"]  // getting the colors for the thought from the color schema created at the beginning

        return `
<li class="journal-entry" style="background-color: ${color.bg}; color: ${color.text}; border: 2px solid ${color.border};">
    <div class="journal-header">
        <h3 class="card-title">${journal.title}</h3>
        <button class="btn-icon btn-delete" data-id="${journal.id}" title="Delete">
            <span class="material-symbols-outlined" style="pointer-events: none;">delete</span>
        </button>
    </div>
    
    <div class="journal-meta">
        <span class="journal-date">📅 ${journal.date}</span>
        <span class="journal-mood" style="background-color: ${color.bg}; color: ${color.text}; border-color: ${color.border};">
            ${journal.mood}
        </span>
    </div>

    <div class="card-excerpt">
        ${journal.content}
    </div>

    <div class="journal-tags">
        ${journal.tags.map((tag) => `<span class="tag" style="background-color: ${color.border}; color: ${color.text};">#${tag}</span>`).join("")}
    </div>

</li>
`;
    }).join("")

    // what we have done is converted all the array values into an array of li tags and ran a .join() function on the resulting array which will 
    // convert the array like a large string and then we are assigning it to innerHTML of ul (that we have left empty in the html file)


    // adding the delete functionality to every delete button
    journalList.querySelectorAll('.btn-delete').forEach(btn => {
        btn.addEventListener('click', (e) => {
            const id = btn.dataset.id // you can see in line no 117, we have added data-id, we are using that one here, this is how we access
            if (!id) return
            deleteJournalById(id)
            renderJournals()
        })
    })
}

// clear the form
const clearForm = () => {
    title.value = ""
    date.value = new Date().toISOString().split('T')[0]
    mood.value = ""
    tags.value = ""
    content.value = ""
    title.focus() // this will focus our cursor to the title input after the form is cleared
}


// Displaying the journals in the left side
renderJournals()